version: '3.8'
services:

  traefik:
      networks:
          - web-public
      ports:
        - "80:80"
        - "443:443"
      deploy:
        update_config:
          parallelism: 1
          delay: 5s
          order: stop-first
        placement:
          constraints:
            - node.role==manager
      volumes:
        # Add Docker as a mounted volume, so that Traefik can read the labels of other services
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - certificates:/certificates
      configs:
        - source: traefik
          target: /etc/traefik/traefik.yml

  mariadb:
    networks:
      - web-public
    environment:
        MARIADB_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
        MARIADB_DATABASE: "${DB_NAME}"
        MARIADB_USER: "${DB_USERNAME}"
        MARIADB_PASSWORD: "${DB_PASSWORD}"
    deploy:
      placement:
        constraints:
          - node.role==manager
    volumes:
      - database_data:/var/lib/mysql
      - database_custom_conf:/etc/mysql/conf.d
      - database_shared:/shared

  ssh:
    # We use an SSH image so we can securely tunnel into the Docker network with 
    # tools like Sequel Pro, TablePlus, Sequel Ace, etc.
    # Learn more how to secure your tunnel here: https://github.com/serversideup/docker-ssh
    image: serversideup/docker-ssh
    ports:
      - target: 2222
        published: 2222
        mode: host
    environment:
      # Change the keys below to your own keys 
      AUTHORIZED_KEYS: >
        "# Start Keys
         ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQChAZM4K0T5zUU+mxm4fpbNQScCxRXfipom0cOXPyyGXh8eTCJLu2vaeCQli4cd/2y51JwAun9O2go6ejPS5ETXDFm+E9K/LKE3Ea0k/W4ol6fOuBzILNdedJI2rltpqv8w9K8Xn+VrvK/q7zF2JzkajZxHknwKTGhbllVoM8RZRRUYJSj7EYyAeZCYXLAH4DacxV4yWyhY/cca5YRRFnnxuvVByvBp87eN6Yt/6FwwV1pp7p6mx9S80xlJQP/T3nk7EEGOQpC9RW82aNk0IjZsbZnF0RNob9f8z50JjF+M9iDz5wkzO+9WThOohwFXgmXsCl5Dw8HauLUOc46019m38tXR5j62vZuc6jWvqKm8WffxMtg8P/3uhiuKOPNV0fFlfVOh2pOnHCN5JmMZr6KHcYfeeeH5nOeiKQx3vx4ndh1ZVoRuZgs0WrXGgYZd56NAxB4zXyvnQs4MeZQBeZAma+1v6Hw1Vs0tiozn6JoXbDmWAeqsCe0yVaV0dllJZoE= mathewparet@gMac.local
         # End Keys"
      # Be sure to configure the allowed IP addresses too
      ALLOWED_IPS: "AllowUsers *@*"
    volumes:
      - tunnel_ssh_host_keys:/etc/ssh/ssh_host_keys
    networks:
        - web-public

  php:
    image: ${DEPLOYMENT_IMAGE_PHP} # 👈 Be sure to change this to your own image
    networks:
      - web-public
    volumes:
      - "storage_private:/var/www/html/storage/app/private/"
      - "storage_public:/var/www/html/storage/app/public/"
      - "storage_sessions:/var/www/html/storage/framework/sessions"
      - "storage_logs:/var/www/html/storage/logs"
    environment:
      PHP_POOL_NAME: "my-php-app"
      AUTORUN_ENABLED: "true"
      AUTORUN_LARAVEL_MIGRATION: "true"
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 5s
        order: start-first
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.my-php-app.rule=${TRAEFIK_HOST_RULE}"
        - "traefik.http.routers.my-php-app.entrypoints=websecure"
        - "traefik.http.routers.my-php-app.tls=true"
        - "traefik.http.routers.my-php-app.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.my-php-app.loadbalancer.server.port=80"
        - "traefik.http.services.my-php-app.loadbalancer.server.scheme=http"
        # Health check
        - "traefik.http.services.my-php-app.loadbalancer.healthcheck.path=/ping"
        - "traefik.http.services.my-php-app.loadbalancer.healthcheck.interval=100ms"
        - "traefik.http.services.my-php-app.loadbalancer.healthcheck.timeout=75ms"
        - "traefik.http.services.my-php-app.loadbalancer.healthcheck.scheme=http"

  task:
    image: ${DEPLOYMENT_IMAGE_PHP}
    # Switch to "webuser" before running `php artisan`
    # Declare command in list manner for environment variable expansion
    # command: ["su", "www-data", "-c", "php artisan schedule:work"]
    command: ["php", "artisan", "schedule:work"]
    environment:
      PHP_FPM_POOL_NAME: "my-app_task"

  queue:
    image: ${DEPLOYMENT_IMAGE_PHP}
    # Switch to "webuser" before running `php artisan`
    # Declare command in list manner for environment variable expansion
    # command: ["su", "www-data", "-c", "php artisan queue:work --tries=3"]
    command: ["php", "artisan", "queue:work"]
    environment:
      PHP_FPM_POOL_NAME: "my-app_queue"

configs:
  traefik:
    name: "traefik.yml"
    file: ./.infrastructure/conf/traefik/prod/traefik.yml

volumes:
  certificates:
  database_data:
  database_custom_conf:
  database_shared:
  storage_private:
  storage_public:
  storage_sessions:
  storage_logs:
  tunnel_ssh_host_keys:

networks:
  web-public:
